# Generated by requirement-importance-less-strict-v1
from __future__ import annotations

import unittest

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
)


class RequirementImportanceLessStrictTests(unittest.TestCase):
    def _rows(self, heading: str, *lines: str) -> dict[str, str]:
        result = canonicalise_requirements(
            jd_profile={},
            raw_jd_text=(
                heading
                + ":\n"
                + "\n".join(f"- {line}" for line in lines)
                + "\n"
            ),
        )
        return {
            str(row.get("text")): str(row.get("importance"))
            for row in result.get("requirements", [])
        }

    def test_generic_requirements_are_not_blanket_required(self) -> None:
        rows = self._rows(
            "Requirements",
            "Experience with full-stack agile software development and CI/CD",
            "Solid understanding of DevSecOps practices",
            (
                "Familiarity with cloud and on-prem security best practices, "
                "threat modeling and compliance"
            ),
            "Strong problem-solving skills",
            "Ability to troubleshoot complex issues",
            "Excellent communication and collaboration skills",
            "Ability to work in a fast-paced, dynamic environment",
            (
                "Continuous learning mindset to keep up with technological "
                "advancements"
            ),
            "Preferably 1-5 years of relevant working experience",
        )

        self.assertEqual(
            rows["Experience with full-stack agile software development and CI/CD"],
            "core",
        )
        self.assertEqual(rows["Solid understanding of DevSecOps practices"], "core")
        for text in (
            "Familiarity with cloud and on-prem security best practices",
            "Familiarity with threat modeling",
            "Familiarity with compliance",
        ):
            self.assertEqual(rows[text], "supporting")
        self.assertEqual(rows["Strong problem-solving skills"], "supporting")
        self.assertEqual(rows["Ability to troubleshoot complex issues"], "core")
        self.assertEqual(
            rows["Excellent communication and collaboration skills"],
            "supporting",
        )
        self.assertEqual(
            rows["Ability to work in a fast-paced, dynamic environment"],
            "supporting",
        )
        self.assertEqual(
            rows[
                "Continuous learning mindset to keep up with technological "
                "advancements"
            ],
            "supporting",
        )
        self.assertEqual(
            rows["Preferably 1-5 years of relevant working experience"],
            "preferred",
        )

    def test_explicit_hard_language_is_required(self) -> None:
        rows = self._rows(
            "Requirements",
            "Must have strong communication and collaboration skills",
            "Minimum 3 years of Python development experience",
            "DevSecOps knowledge is mandatory",
        )
        for importance in rows.values():
            self.assertEqual(importance, "required")

    def test_hard_requirement_heading_preserves_required(self) -> None:
        rows = self._rows(
            "Required Qualifications",
            "Experience with full-stack agile software development and CI/CD",
            "Excellent communication and collaboration skills",
            "Familiarity with cloud security best practices",
        )
        for importance in rows.values():
            self.assertEqual(importance, "required")

    def test_generic_qualifications_heading_is_core_default(self) -> None:
        rows = self._rows(
            "Qualifications",
            "Experience with production CI/CD pipelines",
            "Solid understanding of DevSecOps practices",
        )
        self.assertEqual(
            rows["Experience with production CI/CD pipelines"],
            "core",
        )
        self.assertEqual(
            rows["Solid understanding of DevSecOps practices"],
            "core",
        )

    def test_scoring_version(self) -> None:
        self.assertEqual(
            SCORING_VERSION,
            "stable-evidence-v1.13-phase6d20",
        )


if __name__ == "__main__":
    unittest.main()
