# Generated by requirement-importance-supporting-v1.1
from __future__ import annotations

import unittest

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
    compute_deterministic_alignment,
)
from tailoring.phase9f_starting_source_ranking import IMPORTANT_REQUIREMENTS


class RequirementImportanceSupportingTests(unittest.TestCase):
    def _importance_by_text(self, raw_jd: str) -> dict[str, str]:
        result = canonicalise_requirements(
            jd_profile={},
            raw_jd_text=raw_jd,
        )
        return {
            str(row.get("text")): str(row.get("importance"))
            for row in result.get("requirements", [])
        }

    def test_generic_behavioural_requirements_are_supporting(self) -> None:
        rows = self._importance_by_text(
            "Requirements:\n"
            "Strong problem-solving skills\n"
            "Excellent communication and collaboration skills\n"
            "Ability to work in a fast-paced, dynamic environment\n"
            "Continuous learning mindset to keep up with technological advancements\n"
            "Ability to troubleshoot complex issues\n"
            "Experience with full-stack software development\n"
        )

        self.assertEqual(rows["Strong problem-solving skills"], "supporting")
        self.assertEqual(
            rows["Excellent communication and collaboration skills"],
            "supporting",
        )
        self.assertEqual(
            rows["Ability to work in a fast-paced, dynamic environment"],
            "supporting",
        )
        self.assertEqual(
            rows[
                "Continuous learning mindset to keep up with technological "
                "advancements"
            ],
            "supporting",
        )

        # Functional capability remains a hard requirement.
        self.assertEqual(
            rows["Ability to troubleshoot complex issues"],
            "core",
        )
        self.assertEqual(
            rows["Experience with full-stack software development"],
            "core",
        )

    def test_explicit_required_language_overrides_supporting(self) -> None:
        rows = self._importance_by_text(
            "Requirements:\n"
            "Excellent communication and collaboration skills are mandatory\n"
        )
        self.assertEqual(
            rows[
                "Excellent communication and collaboration skills are mandatory"
            ],
            "required",
        )

    def test_leading_preferably_is_preferred(self) -> None:
        rows = self._importance_by_text(
            "Requirements:\n"
            "Preferably 1-5 years of relevant working experience\n"
        )
        self.assertEqual(
            rows["Preferably 1-5 years of relevant working experience"],
            "preferred",
        )

    def test_profile_only_soft_skills_default_to_supporting(self) -> None:
        result = canonicalise_requirements(
            jd_profile={
                "soft_skills": [
                    "Excellent communication and collaboration skills",
                ],
            },
            raw_jd_text="",
        )
        rows = result.get("requirements", [])
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0]["importance"], "supporting")

    def test_missing_supporting_does_not_reduce_required_coverage(self) -> None:
        hard_only = [
            {
                "requirement_id": "req_hard",
                "atomic_group_id": "grp_hard",
                "importance": "required",
                "match_label": "direct",
                "match_value": 1.0,
                "evidence_strength": 5,
            }
        ]
        with_supporting_gap = hard_only + [
            {
                "requirement_id": "req_support",
                "atomic_group_id": "grp_support",
                "importance": "supporting",
                "match_label": "none",
                "match_value": 0.0,
                "evidence_strength": 0,
            }
        ]

        baseline = compute_deterministic_alignment(hard_only)
        actual = compute_deterministic_alignment(with_supporting_gap)

        self.assertEqual(baseline["required_core_coverage_score"], 100)
        self.assertEqual(actual["required_core_coverage_score"], 100)
        self.assertEqual(
            baseline["deterministic_alignment_score"],
            actual["deterministic_alignment_score"],
        )
        self.assertEqual(actual["supporting_requirement_count"], 1)

    def test_positive_supporting_evidence_can_contribute_to_evidence_strength(
        self,
    ) -> None:
        baseline = compute_deterministic_alignment(
            [
                {
                    "requirement_id": "req_hard",
                    "atomic_group_id": "grp_hard",
                    "importance": "required",
                    "match_label": "direct",
                    "match_value": 1.0,
                    "evidence_strength": 2,
                }
            ]
        )
        with_support = compute_deterministic_alignment(
            [
                {
                    "requirement_id": "req_hard",
                    "atomic_group_id": "grp_hard",
                    "importance": "required",
                    "match_label": "direct",
                    "match_value": 1.0,
                    "evidence_strength": 2,
                },
                {
                    "requirement_id": "req_support",
                    "atomic_group_id": "grp_support",
                    "importance": "supporting",
                    "match_label": "direct",
                    "match_value": 1.0,
                    "evidence_strength": 5,
                },
            ]
        )

        self.assertEqual(with_support["required_core_coverage_score"], 100)
        self.assertGreater(
            with_support["evidence_strength_score"],
            baseline["evidence_strength_score"],
        )

    def test_supporting_is_not_an_important_gap_class(self) -> None:
        self.assertNotIn("supporting", IMPORTANT_REQUIREMENTS)
        self.assertEqual(
            IMPORTANT_REQUIREMENTS,
            {"deal_breaker", "required", "core"},
        )

    def test_scoring_version_is_bumped(self) -> None:
        self.assertEqual(
            SCORING_VERSION,
            "stable-evidence-v1.10-phase6d20",
        )


if __name__ == "__main__":
    unittest.main()
