# Generated by add_application_profile_work_feature.py
# Patch version: application-profile-work-v1

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

import database.application_profile_manager as manager


class ApplicationProfileManagerTests(unittest.TestCase):
    def setUp(self) -> None:
        self._old_db_path = manager.DB_PATH
        self._tmp = tempfile.TemporaryDirectory()
        manager.DB_PATH = Path(self._tmp.name) / "applications.db"

    def tearDown(self) -> None:
        manager.DB_PATH = self._old_db_path
        self._tmp.cleanup()

    def test_default_profile_is_safe_and_unknown(self) -> None:
        profile = manager.get_application_profile()

        self.assertEqual(profile["personal"]["first_name"], "")
        self.assertEqual(
            profile["work_eligibility"]["requires_sponsorship"],
            "",
        )
        completion = manager.application_profile_completion(profile)
        self.assertEqual(completion["completed"], 0)
        self.assertEqual(completion["missing"], completion["total"])

    def test_save_and_reload_round_trip(self) -> None:
        manager.save_application_profile(
            {
                "personal": {
                    "first_name": "Ada",
                    "last_name": "Lovelace",
                    "email": "ada@example.com",
                },
                "work_eligibility": {
                    "requires_sponsorship": "No",
                },
                "preferences": {
                    "preferred_locations": "Singapore",
                },
            }
        )

        profile = manager.get_application_profile()
        self.assertEqual(profile["personal"]["first_name"], "Ada")
        self.assertEqual(profile["personal"]["last_name"], "Lovelace")
        self.assertEqual(profile["personal"]["email"], "ada@example.com")
        self.assertEqual(
            profile["work_eligibility"]["requires_sponsorship"],
            "No",
        )
        self.assertEqual(
            profile["preferences"]["preferred_locations"],
            "Singapore",
        )

    def test_unknown_values_are_explicit_in_work_markdown(self) -> None:
        text = manager.build_work_application_markdown(
            {
                "personal": {"first_name": "Ada"},
            }
        )

        self.assertIn("- First name: Ada", text)
        self.assertIn(
            f"- Last name: {manager.UNKNOWN_LABEL}",
            text,
        )
        self.assertIn("UNKNOWN / ASK ME", text)
        self.assertIn("DO NOT SUBMIT", text)

    def test_work_export_does_not_turn_evidence_into_candidate_facts(self) -> None:
        text = manager.build_work_application_markdown(
            {"personal": {"first_name": "Ada"}},
            evidence_items=[
                {
                    "category": "Project",
                    "title": "Job AI Helper",
                    "description": "Built a grounded resume-analysis workflow.",
                    "skills": ["Python"],
                    "tools": ["Streamlit"],
                    "impact": "Supports application preparation.",
                }
            ],
        )

        self.assertIn("Project: Job AI Helper", text)
        self.assertIn("Python", text)
        self.assertIn("Streamlit", text)
        self.assertIn(
            f"- Requires sponsorship: {manager.UNKNOWN_LABEL}",
            text,
        )

    def test_payload_lists_unknown_fields(self) -> None:
        payload = manager.build_work_application_payload(
            {
                "personal": {
                    "first_name": "Ada",
                    "last_name": "Lovelace",
                }
            }
        )

        self.assertEqual(
            payload["application_profile"]["personal"]["first_name"],
            "Ada",
        )
        self.assertIn("Requires sponsorship", payload["unknown_fields"])
        self.assertTrue(
            any(
                "Do not submit" in instruction
                for instruction in payload["instructions"]
            )
        )

    def test_payload_is_json_serializable(self) -> None:
        payload = manager.build_work_application_payload(
            {"personal": {"first_name": "Ada"}},
            evidence_items=[{"category": "Project", "title": "Example"}],
        )
        encoded = json.dumps(payload, ensure_ascii=False)
        self.assertIn("Ada", encoded)
        self.assertIn("Example", encoded)

    def test_unknown_extra_keys_are_not_persisted(self) -> None:
        manager.save_application_profile(
            {
                "personal": {
                    "first_name": "Ada",
                    "secret_field": "must-not-survive",
                },
                "unexpected_section": {
                    "anything": "ignored",
                },
            }
        )
        profile = manager.get_application_profile()

        self.assertNotIn("secret_field", profile["personal"])
        self.assertNotIn("unexpected_section", profile)

    def test_repeated_schema_initialization_is_idempotent(self) -> None:
        manager.init_application_profile_schema()
        manager.init_application_profile_schema()
        manager.save_application_profile(
            {"personal": {"first_name": "Ada"}}
        )
        manager.init_application_profile_schema()

        self.assertEqual(
            manager.get_application_profile()["personal"]["first_name"],
            "Ada",
        )


if __name__ == "__main__":
    unittest.main()
