# Generated by requirement-importance-preference-split-phase6d20-v1
from __future__ import annotations

import unittest

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
)


class RequirementImportancePreferenceSplitTests(unittest.TestCase):
    def _rows(self, raw_jd: str) -> dict[str, str]:
        result = canonicalise_requirements(
            jd_profile={},
            raw_jd_text=raw_jd,
        )
        return {
            str(row.get("text")): str(row.get("importance"))
            for row in result.get("requirements", [])
        }

    def test_hard_prefix_and_independent_preferred_tail_split_correctly(self) -> None:
        rows = self._rows(
            """
Requirements:
- Must have Python backend experience, preferably FastAPI web framework development experience
"""
        )
        self.assertEqual(
            rows["Must have Python backend experience"],
            "required",
        )
        self.assertEqual(
            rows["FastAPI web framework development experience"],
            "preferred",
        )

    def test_context_only_preference_tail_does_not_downgrade_required_parent(self) -> None:
        rows = self._rows(
            """
Requirements:
- Must have Python backend experience, preferably with FastAPI in production
"""
        )
        self.assertEqual(len(rows), 1)
        self.assertEqual(
            rows[
                "Must have Python backend experience, preferably with FastAPI in production"
            ],
            "required",
        )

    def test_hard_heading_stays_required_with_context_only_preference_tail(self) -> None:
        rows = self._rows(
            """
Required Qualifications:
- Python backend development, preferably in production services
"""
        )
        self.assertEqual(len(rows), 1)
        self.assertEqual(
            rows[
                "Python backend development, preferably in production services"
            ],
            "required",
        )

    def test_non_hard_base_stays_core_when_preference_tail_is_context_only(self) -> None:
        rows = self._rows(
            """
Requirements:
- Python backend development, preferably in production services
"""
        )
        self.assertEqual(len(rows), 1)
        self.assertEqual(
            rows[
                "Python backend development, preferably in production services"
            ],
            "core",
        )

    def test_scoring_version(self) -> None:
        self.assertEqual(
            SCORING_VERSION,
            "stable-evidence-v1.10-phase6d20",
        )


if __name__ == "__main__":
    unittest.main()
