# Generated by requirement-importance-context-supporting-phase6d19-v1
from __future__ import annotations

import unittest

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
)


class RequirementImportanceContextSupportingTests(unittest.TestCase):
    def _by_text(self, raw_jd: str) -> dict[str, dict]:
        result = canonicalise_requirements(
            jd_profile={},
            raw_jd_text=raw_jd,
        )
        return {
            str(row.get("text")): row
            for row in result.get("requirements", [])
        }

    def test_real_export_context_rows_become_supporting(self) -> None:
        rows = self._by_text(
            """
You will be part of a project team to deliver project objectives based on your role trained. You will work closely with project manager, technical lead and architect as part of the project delivery.

Responsibilities:
- Collaborate with other developers and engineers to specify, design, build, and maintain software applications
- Perform software implementation and testing
- Analyze and troubleshoot software issues
- Generate relevant documentations, reports etc
- Contribute to continuous improvement of software development best practices
- Keeping up-to-date with industry trends and technology developments

Requirements:
- Ability to learn new software and technologies quickly
- A good team player who contribute and work effectively in a collaborative team environment
"""
        )

        supporting = (
            "part of a project team to deliver project objectives based on your role trained",
            "work closely with project manager, technical lead and architect as part of the project delivery",
            "Contribute to continuous improvement of software development best practices",
            "Keeping up-to-date with industry trends and technology developments",
            "Ability to learn new software and technologies quickly",
            "A good team player who contribute and work effectively in a collaborative team environment",
        )
        for text in supporting:
            with self.subTest(text=text):
                self.assertEqual(rows[text]["importance"], "supporting")

        core = (
            "Collaborate with other developers and engineers to specify, design, build, and maintain software applications",
            "Perform software implementation and testing",
            "Analyze and troubleshoot software issues",
            "Generate relevant documentations, reports etc",
        )
        for text in core:
            with self.subTest(text=text):
                self.assertEqual(rows[text]["importance"], "core")

    def test_explicit_hard_wording_still_overrides_supporting(self) -> None:
        rows = self._by_text(
            """
Requirements:
- Must be a good team player who works effectively in a collaborative team environment
- Ability to learn new software and technologies quickly is mandatory
"""
        )
        self.assertEqual(
            rows[
                "Must be a good team player who works effectively in a collaborative team environment"
            ]["importance"],
            "required",
        )
        self.assertEqual(
            rows[
                "Ability to learn new software and technologies quickly is mandatory"
            ]["importance"],
            "required",
        )

    def test_preferred_wording_still_overrides_supporting(self) -> None:
        rows = self._by_text(
            """
Requirements:
- A good team player is preferred
- Ability to learn new software and technologies quickly is highly desired
"""
        )
        self.assertEqual(
            rows["A good team player is preferred"]["importance"],
            "preferred",
        )
        self.assertEqual(
            rows[
                "Ability to learn new software and technologies quickly is highly desired"
            ]["importance"],
            "preferred",
        )

    def test_scoring_version(self) -> None:
        self.assertEqual(
            SCORING_VERSION,
            "stable-evidence-v1.10-phase6d20",
        )


if __name__ == "__main__":
    unittest.main()
