# Generated by add_application_profile_work_feature.py
# Patch version: application-profile-work-v1
"""Streamlit UI for the persistent Application Profile and Work export."""

from __future__ import annotations

import json
from typing import Any

import streamlit as st

from database.application_profile_manager import (
    application_profile_completion,
    build_work_application_markdown,
    build_work_application_payload,
    get_application_profile,
    init_application_profile_schema,
    save_application_profile,
)
from database.user_profile_manager import get_evidence_items


_UNKNOWN_OPTION = "Unknown / ask me"
_YES_NO_OPTIONS = [_UNKNOWN_OPTION, "Yes", "No"]


def _tri_state_index(value: Any) -> int:
    cleaned = str(value or "").strip().lower()
    if cleaned == "yes":
        return 1
    if cleaned == "no":
        return 2
    return 0


def _tri_state_value(label: str) -> str:
    return "" if label == _UNKNOWN_OPTION else label


def render_application_profile() -> None:
    """Render the local source-of-truth profile used for application autofill."""
    init_application_profile_schema()
    profile = get_application_profile()
    completion = application_profile_completion(profile)

    st.subheader("Application Profile")
    st.caption(
        "Store repeat job-application facts separately from résumé evidence. "
        "Blank answers remain unknown so Work or a future autofill agent must "
        "ask you instead of inventing them."
    )
    st.caption(
        "Do not store passwords, one-time codes, government ID numbers, "
        "bank details, or other secrets here."
    )

    st.progress(completion["percent"] / 100)
    st.caption(
        f"{completion['completed']}/{completion['total']} repeat-application "
        f"fields currently supplied · {completion['missing']} unknown."
    )

    with st.form("application_profile_form"):
        st.markdown("#### Personal / contact")
        personal_col1, personal_col2 = st.columns(2)
        with personal_col1:
            first_name = st.text_input(
                "First name",
                value=profile["personal"]["first_name"],
            )
            preferred_name = st.text_input(
                "Preferred name, optional",
                value=profile["personal"]["preferred_name"],
            )
            email = st.text_input(
                "Email",
                value=profile["personal"]["email"],
            )
            current_location = st.text_input(
                "Current location",
                value=profile["personal"]["current_location"],
                placeholder="Example: Singapore",
            )
            github_url = st.text_input(
                "GitHub",
                value=profile["personal"]["github_url"],
            )

        with personal_col2:
            last_name = st.text_input(
                "Last name",
                value=profile["personal"]["last_name"],
            )
            phone = st.text_input(
                "Phone",
                value=profile["personal"]["phone"],
            )
            linkedin_url = st.text_input(
                "LinkedIn",
                value=profile["personal"]["linkedin_url"],
            )
            portfolio_url = st.text_input(
                "Portfolio",
                value=profile["personal"]["portfolio_url"],
            )

        st.markdown("#### Work eligibility")
        eligibility_col1, eligibility_col2 = st.columns(2)
        with eligibility_col1:
            work_authorization = st.text_input(
                "Work authorization / status",
                value=profile["work_eligibility"]["work_authorization"],
                placeholder=(
                    "Leave blank if you want Work to ask you for each application"
                ),
                help=(
                    "Use your own exact factual wording. The app does not infer "
                    "work authorization from location, nationality, or résumé data."
                ),
            )
        with eligibility_col2:
            sponsorship_label = st.selectbox(
                "Requires sponsorship",
                _YES_NO_OPTIONS,
                index=_tri_state_index(
                    profile["work_eligibility"]["requires_sponsorship"]
                ),
            )

        st.markdown("#### Availability")
        availability_col1, availability_col2 = st.columns(2)
        with availability_col1:
            notice_period = st.text_input(
                "Notice period",
                value=profile["availability"]["notice_period"],
                placeholder="Example: 2 weeks",
            )
        with availability_col2:
            earliest_start_date = st.text_input(
                "Earliest start date",
                value=profile["availability"]["earliest_start_date"],
                placeholder="Example: 15 Sep 2026",
            )

        st.markdown("#### Preferences")
        pref_col1, pref_col2 = st.columns(2)
        with pref_col1:
            preferred_locations = st.text_input(
                "Preferred locations",
                value=profile["preferences"]["preferred_locations"],
                placeholder="Example: Singapore",
            )
            work_arrangement = st.text_input(
                "Preferred work arrangement",
                value=profile["preferences"]["work_arrangement"],
                placeholder="Example: Hybrid / On-site / Remote",
            )
        with pref_col2:
            relocate_label = st.selectbox(
                "Willing to relocate",
                _YES_NO_OPTIONS,
                index=_tri_state_index(
                    profile["preferences"]["willing_to_relocate"]
                ),
            )
            salary_expectation = st.text_input(
                "Salary expectation",
                value=profile["preferences"]["salary_expectation"],
                placeholder="Leave blank to be asked when needed",
            )

        additional_facts = st.text_area(
            "Additional repeat application facts",
            value=profile["application_defaults"]["additional_facts"],
            height=110,
            placeholder=(
                "Only add factual information you repeatedly need on job forms."
            ),
        )

        save_profile = st.form_submit_button(
            "Save Application Profile",
            type="primary",
        )

        if save_profile:
            save_application_profile(
                {
                    "personal": {
                        "first_name": first_name,
                        "last_name": last_name,
                        "preferred_name": preferred_name,
                        "email": email,
                        "phone": phone,
                        "current_location": current_location,
                        "linkedin_url": linkedin_url,
                        "github_url": github_url,
                        "portfolio_url": portfolio_url,
                    },
                    "work_eligibility": {
                        "work_authorization": work_authorization,
                        "requires_sponsorship": _tri_state_value(
                            sponsorship_label
                        ),
                    },
                    "availability": {
                        "notice_period": notice_period,
                        "earliest_start_date": earliest_start_date,
                    },
                    "preferences": {
                        "preferred_locations": preferred_locations,
                        "work_arrangement": work_arrangement,
                        "willing_to_relocate": _tri_state_value(
                            relocate_label
                        ),
                        "salary_expectation": salary_expectation,
                    },
                    "application_defaults": {
                        "additional_facts": additional_facts,
                    },
                }
            )
            st.success("Application Profile saved.")
            st.rerun()

    with st.expander("Copy / export for ChatGPT Work", expanded=False):
        st.caption(
            "This export is generated locally. The code block has a copy control, "
            "and you can also download Markdown or JSON."
        )
        include_evidence = st.checkbox(
            "Include canonical Profile & Evidence items",
            value=True,
            key="application_profile_include_evidence",
            help=(
                "Include your saved projects/internships/skills as supporting "
                "evidence. Unknown legal, salary, or preference facts still remain "
                "unknown and must not be inferred from this evidence."
            ),
        )
        evidence_items = (
            get_evidence_items(limit=100)
            if include_evidence
            else []
        )
        current_profile = get_application_profile()
        work_markdown = build_work_application_markdown(
            current_profile,
            evidence_items=evidence_items,
        )
        work_payload = build_work_application_payload(
            current_profile,
            evidence_items=evidence_items,
        )

        st.code(work_markdown, language="text")

        download_md_col, download_json_col = st.columns(2)
        with download_md_col:
            st.download_button(
                "Download Work Profile (.md)",
                data=work_markdown,
                file_name="job_ai_helper_work_profile.md",
                mime="text/markdown",
                width="stretch",
            )
        with download_json_col:
            st.download_button(
                "Download Work Profile (.json)",
                data=json.dumps(
                    work_payload,
                    ensure_ascii=False,
                    indent=2,
                ),
                file_name="job_ai_helper_work_profile.json",
                mime="application/json",
                width="stretch",
            )
