# Generated by add_application_profile_work_feature.py
# Patch version: application-profile-work-v1
"""Persistent candidate application profile and Work-ready exports.

This module is deliberately deterministic and local:
- no model calls
- no inference of missing candidate facts
- blank values remain UNKNOWN for downstream agents
"""

from __future__ import annotations

import json
import sqlite3
from copy import deepcopy
from datetime import datetime
from pathlib import Path
from typing import Any


DB_PATH = Path("data/applications.db")
APPLICATION_PROFILE_VERSION = 1
UNKNOWN_LABEL = "UNKNOWN — ask user"

APPLICATION_PROFILE_DEFAULTS: dict[str, dict[str, str]] = {
    "personal": {
        "first_name": "",
        "last_name": "",
        "preferred_name": "",
        "email": "",
        "phone": "",
        "current_location": "",
        "linkedin_url": "",
        "github_url": "",
        "portfolio_url": "",
    },
    "work_eligibility": {
        "work_authorization": "",
        "requires_sponsorship": "",
    },
    "availability": {
        "notice_period": "",
        "earliest_start_date": "",
    },
    "preferences": {
        "preferred_locations": "",
        "work_arrangement": "",
        "willing_to_relocate": "",
        "salary_expectation": "",
    },
    "application_defaults": {
        "additional_facts": "",
    },
}

PROFILE_FIELD_LABELS: tuple[tuple[str, str, str], ...] = (
    ("personal", "first_name", "First name"),
    ("personal", "last_name", "Last name"),
    ("personal", "preferred_name", "Preferred name"),
    ("personal", "email", "Email"),
    ("personal", "phone", "Phone"),
    ("personal", "current_location", "Current location"),
    ("personal", "linkedin_url", "LinkedIn"),
    ("personal", "github_url", "GitHub"),
    ("personal", "portfolio_url", "Portfolio"),
    ("work_eligibility", "work_authorization", "Work authorization / status"),
    ("work_eligibility", "requires_sponsorship", "Requires sponsorship"),
    ("availability", "notice_period", "Notice period"),
    ("availability", "earliest_start_date", "Earliest start date"),
    ("preferences", "preferred_locations", "Preferred locations"),
    ("preferences", "work_arrangement", "Preferred work arrangement"),
    ("preferences", "willing_to_relocate", "Willing to relocate"),
    ("preferences", "salary_expectation", "Salary expectation"),
    ("application_defaults", "additional_facts", "Additional application facts"),
)


def _connect() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    return sqlite3.connect(DB_PATH)


def init_application_profile_schema() -> None:
    """Create the singleton application-profile table if it does not exist."""
    conn = _connect()
    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS user_application_profile (
                id INTEGER PRIMARY KEY CHECK (id = 1),
                profile_version INTEGER NOT NULL,
                profile_json TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


def _normalise_text(value: Any) -> str:
    return str(value or "").strip()


def normalise_application_profile(
    profile: dict[str, Any] | None,
) -> dict[str, dict[str, str]]:
    """Return only supported fields, merged onto stable defaults."""
    result = deepcopy(APPLICATION_PROFILE_DEFAULTS)
    source = profile if isinstance(profile, dict) else {}

    for section, default_fields in APPLICATION_PROFILE_DEFAULTS.items():
        incoming = source.get(section, {})
        if not isinstance(incoming, dict):
            continue
        for field_name in default_fields:
            result[section][field_name] = _normalise_text(
                incoming.get(field_name, "")
            )

    return result


def get_application_profile() -> dict[str, dict[str, str]]:
    """Load the persistent singleton profile, returning defaults when absent."""
    init_application_profile_schema()
    conn = _connect()
    try:
        row = conn.execute(
            """
            SELECT profile_json
            FROM user_application_profile
            WHERE id = 1
            """
        ).fetchone()
    finally:
        conn.close()

    if row is None:
        return deepcopy(APPLICATION_PROFILE_DEFAULTS)

    try:
        payload = json.loads(row[0] or "{}")
    except (TypeError, json.JSONDecodeError):
        payload = {}

    return normalise_application_profile(payload)


def save_application_profile(profile: dict[str, Any]) -> None:
    """Persist the complete supported profile as one versioned JSON document."""
    cleaned = normalise_application_profile(profile)
    payload = json.dumps(cleaned, ensure_ascii=False, sort_keys=True)
    now = datetime.now().isoformat(timespec="seconds")

    init_application_profile_schema()
    conn = _connect()
    try:
        conn.execute(
            """
            INSERT INTO user_application_profile (
                id,
                profile_version,
                profile_json,
                updated_at
            )
            VALUES (1, ?, ?, ?)
            ON CONFLICT(id) DO UPDATE SET
                profile_version = excluded.profile_version,
                profile_json = excluded.profile_json,
                updated_at = excluded.updated_at
            """,
            (
                APPLICATION_PROFILE_VERSION,
                payload,
                now,
            ),
        )
        conn.commit()
    finally:
        conn.close()


def application_profile_completion(
    profile: dict[str, Any] | None = None,
) -> dict[str, int]:
    """Count supplied repeat-application facts without guessing missing values."""
    current = normalise_application_profile(
        profile if profile is not None else get_application_profile()
    )
    total = len(PROFILE_FIELD_LABELS)
    completed = 0

    for section, field_name, _label in PROFILE_FIELD_LABELS:
        if _normalise_text(current[section][field_name]):
            completed += 1

    return {
        "completed": completed,
        "total": total,
        "missing": total - completed,
        "percent": round((completed / total) * 100) if total else 100,
    }


def _display_value(value: Any) -> str:
    cleaned = _normalise_text(value)
    return cleaned if cleaned else UNKNOWN_LABEL


def _unknown_field_labels(
    profile: dict[str, dict[str, str]],
) -> list[str]:
    return [
        label
        for section, field_name, label in PROFILE_FIELD_LABELS
        if not _normalise_text(profile[section][field_name])
    ]


def _evidence_export_items(
    evidence_items: list[dict[str, Any]] | None,
) -> list[dict[str, Any]]:
    exported: list[dict[str, Any]] = []
    for item in evidence_items or []:
        if not isinstance(item, dict):
            continue
        exported.append(
            {
                "category": _normalise_text(item.get("category")),
                "title": _normalise_text(item.get("title")),
                "subtitle": _normalise_text(item.get("subtitle")),
                "period": _normalise_text(item.get("period")),
                "description": _normalise_text(item.get("description")),
                "skills": [
                    _normalise_text(value)
                    for value in (item.get("skills") or [])
                    if _normalise_text(value)
                ],
                "tools": [
                    _normalise_text(value)
                    for value in (item.get("tools") or [])
                    if _normalise_text(value)
                ],
                "impact": _normalise_text(item.get("impact")),
            }
        )
    return exported


def build_work_application_payload(
    profile: dict[str, Any] | None = None,
    *,
    evidence_items: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build a machine-readable source-of-truth payload for Work/browser agents."""
    current = normalise_application_profile(
        profile if profile is not None else get_application_profile()
    )
    return {
        "profile_version": APPLICATION_PROFILE_VERSION,
        "instructions": [
            "Treat explicit candidate facts in this payload as source-of-truth facts.",
            f"If a value is blank or missing, treat it as {UNKNOWN_LABEL}.",
            "Do not infer legal/work-authorization, sponsorship, salary, demographic, security-clearance, or availability answers from the resume or other evidence.",
            "Use evidence only to support experience, project, skill, education, or achievement claims that it actually contains.",
            "If an application asks for a fact that is not supported here, stop and ask the user.",
            "Do not submit the job application; stop for user review.",
        ],
        "application_profile": current,
        "unknown_fields": _unknown_field_labels(current),
        "evidence_library": _evidence_export_items(evidence_items),
    }


def build_work_application_markdown(
    profile: dict[str, Any] | None = None,
    *,
    evidence_items: list[dict[str, Any]] | None = None,
) -> str:
    """Build a human-readable copy/paste profile for ChatGPT Work."""
    current = normalise_application_profile(
        profile if profile is not None else get_application_profile()
    )

    lines = [
        "# JOB AI HELPER — CANDIDATE APPLICATION PROFILE",
        "",
        "## SOURCE-OF-TRUTH RULES",
        "- Use the explicit candidate facts below when filling job applications.",
        f"- `{UNKNOWN_LABEL}` means stop and ask me; do not guess.",
        "- Do not infer work authorization, sponsorship, salary, demographic answers, security clearance, or availability from my résumé.",
        "- Use the evidence section only for claims it actually supports.",
        "- If an application asks for an unsupported fact, ask me.",
        "- Fill and navigate the application as needed, but DO NOT SUBMIT it.",
        "- Stop on the final review step so I can verify every answer.",
        "",
    ]

    sections = (
        ("PERSONAL / CONTACT", "personal"),
        ("WORK ELIGIBILITY", "work_eligibility"),
        ("AVAILABILITY", "availability"),
        ("PREFERENCES", "preferences"),
        ("APPLICATION DEFAULTS", "application_defaults"),
    )

    label_map = {
        (section, field_name): label
        for section, field_name, label in PROFILE_FIELD_LABELS
    }

    for heading, section in sections:
        lines.append(f"## {heading}")
        for field_name in APPLICATION_PROFILE_DEFAULTS[section]:
            label = label_map[(section, field_name)]
            value = _display_value(current[section][field_name])
            lines.append(f"- {label}: {value}")
        lines.append("")

    unknowns = _unknown_field_labels(current)
    lines.append("## UNKNOWN / ASK ME")
    if unknowns:
        for label in unknowns:
            lines.append(f"- {label}")
    else:
        lines.append("- None in the saved Application Profile.")
    lines.append("")

    exported_evidence = _evidence_export_items(evidence_items)
    lines.append("## CANONICAL EVIDENCE FROM JOB AI HELPER")
    if not exported_evidence:
        lines.append("- No evidence items included in this export.")
    else:
        for item in exported_evidence:
            title = item["title"] or "Untitled evidence"
            category = item["category"] or "Evidence"
            lines.append(f"### {category}: {title}")
            if item["subtitle"]:
                lines.append(f"- Subtitle: {item['subtitle']}")
            if item["period"]:
                lines.append(f"- Period: {item['period']}")
            if item["description"]:
                lines.append("- Evidence:")
                for raw_line in item["description"].splitlines():
                    cleaned = raw_line.lstrip("•-* ").strip()
                    if cleaned:
                        lines.append(f"  - {cleaned}")
            if item["skills"]:
                lines.append("- Supported skills: " + ", ".join(item["skills"]))
            if item["tools"]:
                lines.append("- Tools/technologies: " + ", ".join(item["tools"]))
            if item["impact"]:
                lines.append(f"- Impact/scope: {item['impact']}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"
