# Generated by requirement-importance-supporting-v1.1
from __future__ import annotations

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
)
from tailoring.phase9f_starting_source_ranking import IMPORTANT_REQUIREMENTS


def main() -> None:
    raw_jd = (
        "Requirements:\n"
        "Strong problem-solving skills\n"
        "Ability to troubleshoot complex issues\n"
        "Excellent communication and collaboration skills\n"
        "Ability to work in a fast-paced, dynamic environment\n"
        "Continuous learning mindset to keep up with technological advancements\n"
        "Preferably 1-5 years of relevant working experience\n"
    )
    result = canonicalise_requirements(
        jd_profile={},
        raw_jd_text=raw_jd,
    )
    rows = {
        str(row.get("text")): str(row.get("importance"))
        for row in result.get("requirements", [])
    }
    expected = {
        "Strong problem-solving skills": "supporting",
        "Ability to troubleshoot complex issues": "core",
        "Excellent communication and collaboration skills": "supporting",
        "Ability to work in a fast-paced, dynamic environment": "supporting",
        (
            "Continuous learning mindset to keep up with technological "
            "advancements"
        ): "supporting",
        "Preferably 1-5 years of relevant working experience": "preferred",
    }

    if rows != expected:
        raise SystemExit(
            "Requirement importance smoke check failed.\n"
            f"Expected: {expected}\n"
            f"Actual:   {rows}"
        )
    if "supporting" in IMPORTANT_REQUIREMENTS:
        raise SystemExit(
            "supporting must not be counted as an important-gap class"
        )
    if SCORING_VERSION != "stable-evidence-v1.15-phase6d20":
        raise SystemExit(
            f"Unexpected scoring version: {SCORING_VERSION!r}"
        )

    print("REQUIREMENT IMPORTANCE SUPPORTING: PASS")
    print(f"Scoring version: {SCORING_VERSION}")
    print("Supporting: problem-solving, communication, fast-paced, learning")
    print("Core: troubleshooting")
    print("Preferred: leading Preferably experience statement")


if __name__ == "__main__":
    main()
