# Generated by requirement-importance-preference-split-phase6d20-v1
from __future__ import annotations

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
)


def rows(raw_jd: str) -> dict[str, str]:
    result = canonicalise_requirements(
        jd_profile={},
        raw_jd_text=raw_jd,
    )
    return {
        str(row.get("text")): str(row.get("importance"))
        for row in result.get("requirements", [])
    }


def main() -> None:
    split_rows = rows(
        """
Requirements:
- Must have Python backend experience, preferably FastAPI web framework development experience
"""
    )
    context_rows = rows(
        """
Requirements:
- Must have Python backend experience, preferably with FastAPI in production
"""
    )

    errors: list[str] = []

    if split_rows.get("Must have Python backend experience") != "required":
        errors.append(
            "hard prefix was not preserved as required in mixed preference split"
        )
    if split_rows.get("FastAPI web framework development experience") != "preferred":
        errors.append("independent preference tail was not preferred")

    context_text = (
        "Must have Python backend experience, preferably with FastAPI in production"
    )
    if context_rows.get(context_text) != "required":
        errors.append(
            "context-only preference tail downgraded its required parent"
        )

    if SCORING_VERSION != "stable-evidence-v1.15-phase6d20":
        errors.append(f"unexpected scoring version: {SCORING_VERSION!r}")

    if errors:
        raise SystemExit(
            "PREFERENCE SPLIT CHECK: FAIL\n- " + "\n- ".join(errors)
        )

    print("PREFERENCE SPLIT CHECK: PASS")
    print(f"Scoring version: {SCORING_VERSION}")
    print("Hard prefix -> required")
    print("Independent preference tail -> preferred")
    print("Context-only preference tail preserves parent importance")


if __name__ == "__main__":
    main()
