# Generated by requirement-importance-context-supporting-phase6d19-v1
from __future__ import annotations

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
)


def main() -> None:
    raw_jd = """
You will be part of a project team to deliver project objectives based on your role trained. You will work closely with project manager, technical lead and architect as part of the project delivery.

Responsibilities:
- Collaborate with other developers and engineers to specify, design, build, and maintain software applications
- Analyze and troubleshoot software issues
- Generate relevant documentations, reports etc
- Contribute to continuous improvement of software development best practices
- Keeping up-to-date with industry trends and technology developments

Requirements:
- Ability to learn new software and technologies quickly
- A good team player who contribute and work effectively in a collaborative team environment
"""
    result = canonicalise_requirements(
        jd_profile={},
        raw_jd_text=raw_jd,
    )
    rows = {
        str(row.get("text")): str(row.get("importance"))
        for row in result.get("requirements", [])
    }

    expected_supporting = (
        "part of a project team to deliver project objectives based on your role trained",
        "work closely with project manager, technical lead and architect as part of the project delivery",
        "Contribute to continuous improvement of software development best practices",
        "Keeping up-to-date with industry trends and technology developments",
        "Ability to learn new software and technologies quickly",
        "A good team player who contribute and work effectively in a collaborative team environment",
    )
    expected_core = (
        "Collaborate with other developers and engineers to specify, design, build, and maintain software applications",
        "Analyze and troubleshoot software issues",
        "Generate relevant documentations, reports etc",
    )

    errors: list[str] = []
    for text in expected_supporting:
        if rows.get(text) != "supporting":
            errors.append(
                f"expected supporting: {text!r}; got {rows.get(text)!r}"
            )
    for text in expected_core:
        if rows.get(text) != "core":
            errors.append(
                f"expected core: {text!r}; got {rows.get(text)!r}"
            )

    if SCORING_VERSION != "stable-evidence-v1.14-phase6d20":
        errors.append(f"unexpected scoring version: {SCORING_VERSION!r}")

    if errors:
        raise SystemExit(
            "CONTEXT SUPPORTING CHECK: FAIL\n- " + "\n- ".join(errors)
        )

    print("CONTEXT SUPPORTING CHECK: PASS")
    print(f"Scoring version: {SCORING_VERSION}")
    print("Supporting context rows: 6")
    print("Concrete technical/deliverable rows remain core")


if __name__ == "__main__":
    main()
