# Generated by requirement-importance-less-strict-v1
from __future__ import annotations

from analysis_stability.stable_evidence_scoring import (
    SCORING_VERSION,
    canonicalise_requirements,
)


def main() -> None:
    raw_jd = (
        "Requirements:\n"
        "- Experience with full-stack agile software development and CI/CD\n"
        "- Solid understanding of DevSecOps practices\n"
        "- Familiarity with cloud and on-prem security best practices, threat modeling and compliance\n"
        "- Strong problem-solving skills\n"
        "- Ability to troubleshoot complex issues\n"
        "- Excellent communication and collaboration skills\n"
        "- Ability to work in a fast-paced, dynamic environment\n"
        "- Continuous learning mindset to keep up with technological advancements\n"
        "- Preferably 1-5 years of relevant working experience\n"
    )
    result = canonicalise_requirements(
        jd_profile={},
        raw_jd_text=raw_jd,
    )
    actual = {
        str(row.get("text")): str(row.get("importance"))
        for row in result.get("requirements", [])
    }
    expected = {
        "Experience with full-stack agile software development and CI/CD": "core",
        "Solid understanding of DevSecOps practices": "core",
        "Familiarity with cloud and on-prem security best practices": "supporting",
        "Familiarity with threat modeling": "supporting",
        "Familiarity with compliance": "supporting",
        "Strong problem-solving skills": "supporting",
        "Ability to troubleshoot complex issues": "core",
        "Excellent communication and collaboration skills": "supporting",
        "Ability to work in a fast-paced, dynamic environment": "supporting",
        (
            "Continuous learning mindset to keep up with technological "
            "advancements"
        ): "supporting",
        "Preferably 1-5 years of relevant working experience": "preferred",
    }

    if actual != expected:
        raise SystemExit(
            "LESS-STRICT REQUIREMENT IMPORTANCE: FAIL\n"
            f"Expected: {expected}\nActual:   {actual}"
        )

    hard = canonicalise_requirements(
        jd_profile={},
        raw_jd_text=(
            "Required Qualifications:\n"
            "Experience with full-stack agile software development and CI/CD\n"
            "Excellent communication and collaboration skills\n"
        ),
    )
    if any(
        row.get("importance") != "required"
        for row in hard.get("requirements", [])
    ):
        raise SystemExit(
            "Hard Required Qualifications heading did not preserve required."
        )

    if SCORING_VERSION != "stable-evidence-v1.15-phase6d20":
        raise SystemExit(
            f"Unexpected scoring version: {SCORING_VERSION!r}"
        )

    print("REQUIREMENT IMPORTANCE LESS STRICT: PASS")
    print(f"Scoring version: {SCORING_VERSION}")
    print("Generic Requirements: technical capability -> core")
    print("Generic Requirements: behavioural/familiarity -> supporting")
    print("Explicit hard wording/heading -> required")
    print("Preferably -> preferred")


if __name__ == "__main__":
    main()
